import asyncio
import logging
from backend.pipeline.discovery_pipeline import ProductionPipeline

# TURN ON LOGS: This allows us to watch the AI process the gigabytes of data
logging.basicConfig(level=logging.INFO, format="%(message)s")
logger = logging.getLogger("DiscoveryEngine")

async def run_groundbreaking_discovery():
    print("="*65)
    print("🧬 INITIALIZING AI DISCOVERY ENGINE v5.0")
    print("="*65)
    
    pipeline = ProductionPipeline()
    await pipeline.initialize(disease="dipg")
    
    print("\n🔬 Scanning Human Pharmacopeia & Raw Omics...")
    results = await pipeline.run(disease_name="dipg", top_k=15)
    
    print("\n" + "="*65)
    print("🏆 GROUNDBREAKING DISCOVERY RESULTS")
    print("="*65)
    
    # Print the dynamic report generated by hypothesis_generator
    report = pipeline._hyp_gen.generate_report(results.get("hypotheses", []))
    print(report)

if __name__ == "__main__":
    asyncio.run(run_groundbreaking_discovery())